### ISSUE TITLE
How to retrieve parameters from OpenId Connect in Angular 6

### ISSUE THREAD

**Issue by nukalaharish** [onelogin/onelogin-oidc-angular#1]
Hello Team,

I'm currently working on an angular app which is integrated with OpenId Connect app in OneLogin, authentication is done successfully but couldn't figure out how to retrieve parameters from OpenId Connect app. My angular app needs username and email address fields which indeed will be passed in the request body of a web service call. I tried looking for any documentation online but could not find any. Please suggest.

**Comment by richet** [comment]
The information returned in the openid connect id_token is determined by the scopes that are supplied when you kick off the implicit flow. 

You will want to specify scopes `openid profile`. 

OneLogin also supports other scopes which you can read about here https://developers.onelogin.com/openid-connect/scopes

You can experiment with the data returned using our openid connect inspector https://developers.onelogin.com/openid-connect/inspector
